### ISSUE TITLE
On MacOS can't quite get the installation right.

### ISSUE THREAD

**Issue by lcoppenr** [urself25/OrcaSlicer_FF_AD4_Profile#2]
Can't thank you enough for your work on this.  I'm on an M4 Mac (MacOS 15.2) and at this point FlashPrint won't load at all, so this is a life saver.   
I know you don't have a Mac to work on, which is has similar folder structure once you access the "Show Package Contents" in the Applications folder.   I copied in the git repo per the instructions and first couldn't see Adventurer 4 Series on list.  After tweaking the json files and removing references to the Adv3, I was able to get as far as the filament list and that was empty.  I spent quite a bit of time trying to figure that out and I just can't get the filaments to show, which is kind of a show stopper.

I guess I'm wondering if someone could export the printer config to a .orca_printer file and maybe I can import that.   On the Mac version of Orca Slicer, under File-Export-Export Preset Bundle, a .orca_printer can be created.  Only hiccup is that it won't export a listed printer, so each printer profile (ADV4 0.x Nozzle) would need to be modified and saved to a new name.

I'd love to get this working...  I'd like to get another year or so out of my ADV4.  I hate that Flashforge has simply given up on the 4, this completely turned me off of buying a FF printer ever again.

 <img width="615" alt="image" src="https://github.com/user-attachments/assets/c38aafee-4a38-4607-8a53-aa263a7c9aa8">

**Comment by urself25** [comment]
Thanks, I'll try to pull out my old 2012 macbook pro that I have, try to install Orcaslicer and see what are the issues.

I tried to export the presets but I had no config to export when clicking the first option. I think the export option was made to export user presets and not the official one.

**Comment by lcoppenr** [comment]
That is correct that it won't export the official ones without a couple extra steps.  If you modify the printer in some way and save it.  For instance, I changed the Printable Height on the ADV5M to 221, saved it as another name and then edited back to 220.   I can then export it. 

There are two nice byproducts of using this method.  1. It allows anyone to import the printer config.  2. When you perform an upgrade of Orca-Slicer, you can just import the .orca_printer (although I actually think it will keep it in tact since the custom printer is stored in the user profile folder).

<img width="759" alt="image" src="https://github.com/user-attachments/assets/3f24d61b-1179-4657-955d-a8c80e67dfb5">



Again I appreciate your help on this.

**Comment by urself25** [comment]
I just checked and your idea will not work. user saved presets only saved the changes of the system preset and not the whole information. It refers back to the system preset file for the missing data.

I'll try to see what I can do on my old mac tonight.

**Comment by lcoppenr** [comment]
Thanks for checking.  I can understand the reasoning behind not importing all the information.  Still quite annoying.   Adding a 3d printer SHOULD be easier.  Thanks again and if there is anything I can do to help let me know.

**Comment by urself25** [comment]
![20241117_212701](https://github.com/user-attachments/assets/dd86c82f-83cc-4a70-9a1a-333f61a08faa)

Got it.

Make sure that Orcaslicer is closed.

Under here: /Users/<user name>/Library/Application Support/OrcaSlicer/system/
erase the file and folder named Flashforge.

Under this location: /System/Volumes/Data/Applications/OrcaSlicer.app/Contents/Resources/Profiles/
extract the RAR file in this location.

Start Orcaslicer and select the Adventurer 4. All should be there.

Let me know if it works.

**Comment by lcoppenr** [comment]
Performed the setup on two Macs without issue.   The key obviously was I was missing removing the file/folder under /Users//Library/Application Support/OrcaSlicer/system/.  So here is my process:

1. Open OrcaSlicer
2. Goto Help - Show Configuration Folder
3. Leave the Finder windows with the configuration Folder open, but close OrcaSlicer
4. In the Finder window for the Configuration Folder, under System, delete Flashforge.json and the Flashforge folder if they exist.  They existed for me as I had selected the Adv3 just to see what OrcaSlicer was like.  On a clean install they may not exist.
5. Download the repository zip file (automatically extracts to Downloads typically)
6. Select and Copy the Flashforge.json and the Flashforge folder in the newly extracted download.  (don't paste them anywhere yet)
7. Open Finder and the Applications folder
8. Two finger click or Right click on OrcaSlicer application and select Show Package Contents
9. Under Contents/Resources/profiles, Paste the previous copied Flashforge.json and Flashforge folder.
10. You'll be asked to Replace or Merge the Folders.  You want to Merge them
11. Next you will be asked to Keep Both, Stop or Replace Flashforge.json.  Select Replace
12. Open OrcaSlicer
13. You should see the Adventurer 4 in the printer selection list with 0.3, 0.4,0.6 nozzles and generic filaments.

I've printed two benchy(s) both of which came out pretty well.   I am quite happy with the solution...   Awesome work.

As far as getting the GX_Code files to the Adv4 wirelessly, I used https://github.com/andycb/AdventurerClientJS to upload and monitor the printing.  Seemed to work perfectly and it was easier then USB and I didn't need FlashPrint to upload the gx file.    

Now will do some tweaking, but [urself25](https://github.com/urself25) obviously did all the hard work.

**Comment by urself25** [comment]
> As far as getting the GX_Code files to the Adv4 wirelessly, I used https://github.com/andycb/AdventurerClientJS to upload and monitor the printing. Seemed to work perfectly and it was easier then USB and I didn't need FlashPrint to upload the gx file.

Oh! Interesting project. I'll see if I can make something work as an end_process script. No promises. I work in HR. I don't have any programming knowledge. 😆
